### PR TITLE
feat: added item freeze functionality to draggable list

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description

This PR introduces disabling the drag of an item in the draggable list. 

Fixes [PR](https://github.com/appsmithorg/appsmith/pull/18757) [Issue](https://github.com/appsmithorg/appsmith/issues/3265)

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

Manual

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Comment by shadabbuchh** [comment]
Issues noticed:

1. When two or more draggable list items are frozen either on top or at the bottom, the gap between the items vanishes and they stick together.
2. The drag experience is not smooth. Dragging an item towards the bottom pusher it above the item before it.

Please refer the below video for reference:
https://www.loom.com/share/cdb396d49a394254b41f93bb6ee864f8

**Comment by keyurparalkar** [comment]
> Issues noticed:
> 
> 1. When two or more draggable list items are frozen either on top or at the bottom, the gap between the items vanishes and they stick together.
> 2. The drag experience is not smooth. Dragging an item towards the bottom pusher it above the item before it.
> 3. For frozen items we see the same cursor icon that we see for unfrozen items. This can be confusing for the users.
> 
> Please refer the below video for reference: https://www.loom.com/share/cdb396d49a394254b41f93bb6ee864f8

@shadabbuchh issue 1 is resolved. Issue 2 already exists in the prod. 

For issue 3, it is a widget-specific issue i.e. the cursor is managed by the widget that is using it. So I will make changes to the main PR specific to the table widget.

**Review by albinAppsmith — APPROVED** [review]

**Comment by shadabbuchh** [comment]
All issues are fixed.

**Review by albinAppsmith — APPROVED** [review]

**Comment by shadabbuchh** [comment]
@keyurparalkar the `sticky` property now does not shift the list item to the top/bottom based on what value we have given. 
https://www.loom.com/share/9a0ec3a404254533a203aa030bf12aea

**Review by albinAppsmith — APPROVED** [review]

**Comment by shadabbuchh** [comment]
All issue are fixed. The new `isDragDisabled` property is working as expected.

**Pull request merged**
