### PR TITLE
feat: Refactored number input

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

Added number input

Fixes # (issue)
https://github.com/appsmithorg/appsmith/issues/21251

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

- Manual on storybook 
- Manual on main repo
- Jest
- Cypress

### Issues raised during DP testing
https://github.com/appsmithorg/design-system/pull/404#issuecomment-1459711886
https://github.com/appsmithorg/design-system/pull/404#issuecomment-1460049732

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by tanvibhakta — APPROVED** [review]

**Comment by shadabbuchh** [comment]
### Bugs in this PR:

**Functional:**

1. prefix, suffix & className do not render
2. We are able to enter characters other than numbers in the value control
3. Provide more desc for Scale
4. Not able to set Label
5. No control to add disabled state.

**Design:**

1. Length is incorrect. (Is it auto?)
2. Wrong right/left padding for the input area
3. Wrong top/bottom & left padding of the +/- icon

**Comment by albinAppsmith** [comment]
@shadabbuchh fixed all functional bugs.

**Comment by shadabbuchh** [comment]
Issues identified after the fix:

**Functional:**
1. `className` still does not render.
2. We are able to select the value in Disabled state.
3. Suffix does not render even after hard refresh.
4. Can the `Placeholder` control be removed from this component since it is not using one?
5. Should the `isRequired` control be disabled if no Label is present?

**Design:**

1. Opacity not applied to the Label in Disabled state. (For the Input component also we do not have opacity in Label. Should this component also follow suit?)

**Comment by albinAppsmith** [comment]
1. className still does not render. -> FIXED
2. We are able to select the value in Disabled state -> This behaviour is default for input components in HTML.
3. Suffix does not render even after hard refresh. -> Working for me [link](https://design-system-git-ads-v2-number-input-get-appsmith.vercel.app/?path=/story/design-system-input-numberinput--number-input-story&args=suffix:+USD)
4. Can the Placeholder control be removed from this component since it is not using one? -> added support for placeholder
5. Should the isRequired control be disabled if no Label is present? -> We will hide required * if no label present. We cannot disable control since it is part of storybook.

@shadabbuchh Please verify.

**Comment by shadabbuchh** [comment]
@albinAppsmith all the above issues have been fixed.
However after the latest fixes I notice that:

1. The cursor placement when no text is entered is right in the middle of the placeholder.
2. When we add a suffix/prefix, the cursor placement is not intuitive. It shows up at the end (after thee suffix) & not where the text ends.

Please refer to the below video for better clarity:
https://www.loom.com/share/8061c51a4a0047c990360e3f1bcdf061

**Pull request merged**
