### PR TITLE
fix: Adding support for `to` prop even when `onClick` prop is being sent

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

Adding support for `to` prop even when `onClick` prop is being sent.

Fixes [#583](https://github.com/appsmithorg/design-system/issues/583)

Depends on [#2252](https://github.com/appsmithorg/appsmith-ee/pull/2252) [#27223](https://github.com/appsmithorg/appsmith/pull/27223) [#1312](https://github.com/appsmithorg/cloud-services/pull/1312)
> every PR in the design-system repository should have a corresponding PR in the appsmith repository to ensure that changes 
> here don't break existing flows. Link the corresponding PR here to trigger dpulls and prevent accidental merging.
> If relevant, link the enterprise PR here as well.

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual on storybook 
- Manual on main repo
- Jest
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [x] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by albinAppsmith — DISMISSED** [review]

**Comment by shadabbuchh** [comment]
Tested only the functionality of Link component in this PR. Both `to` & `onClick` work fine mutually.

https://github.com/appsmithorg/design-system/assets/39921438/b56385b6-22d6-489e-9eab-2032fced4df0

**Review by albinAppsmith — DISMISSED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Comment by shadabbuchh** [comment]
Tested this PR with the new changes. Tried out different combinations of `to` & `onClick`. Looks good.
https://www.loom.com/share/f3ba0922bda649dc857dd5f5ae367e17

**Pull request merged**
