### PR TITLE
chore: in avatar, calculate firstLetter from label if passed and make it a fallback

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

Fixes https://github.com/appsmithorg/appsmith/issues/25461

Depends on https://github.com/appsmithorg/appsmith/pull/26067

## Type of change

- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update

## How Has This Been Tested?

- Manual on storybook 
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Comment by Sripriya93** [comment]
1) If we remove the whole url from Image and paste it again, image works fine, but when we remove only one or two text and undo the action, image isnt loading.

2) The first letter component is allowing many characters, as per expectation it should allow only one

So moved it to reopen.



https://images.zenhubusercontent.com/627b57d87180949256bd1e01/99c807f2-05ff-4e74-9b64-c9b6d05362e7)f352cb6808ce/design_system___avatar___docs___storybook___21_july_2023.mp4

**Comment by tanvibhakta** [comment]
> but when we remove only one or two text and undo the action, image isnt loading.

This isn't a real use case when we are using Avatar, because the image will not change before a page render. It is not trivial to handle this limitation, so we should not spend time on this imo.

> The first letter component is allowing many characters, as per expectation it should allow only one

Have changed this to only allow 2 letters to account for the avatar group usecase of `9+`

**Comment by tanvibhakta** [comment]
All tests have passed: https://github.com/appsmithorg/appsmith/pull/26067#issuecomment-1667181580

**Pull request merged**
