### PR TITLE
feat: Added flex component

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

This PR addes the Flex component.

Fixes https://github.com/appsmithorg/appsmith/issues/27607
Fixes https://github.com/appsmithorg/appsmith/issues/27608
Fixes https://github.com/appsmithorg/appsmith/issues/27606

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual on storybook 
- Manual on main repo
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by KelvinOm** [comment]
@albinAppsmith what is the difference between Flex and [Box](https://github.com/appsmithorg/design-system/pull/644) components and what is the reason to have both of them?

**Review by KelvinOm — COMMENTED** [review]
@albinAppsmith what is the difference between Flex and https://github.com/appsmithorg/design-system/pull/644 components and what is the reason to have both of them?

**Comment by albinAppsmith** [comment]
> @albinAppsmith what is the difference between Flex and #644 components and what is the reason to have both of them?

@KelvinOm I have made the box component as private and not export it outside the package. And for grid and flex I'm using it.

**Review by KelvinOm — COMMENTED** [review]
LGTM. @jsartisan Could you also take a look?

**Review by KelvinOm — DISMISSED** [review]

**Review by jsartisan — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]

**Pull request merged**
