### PR TITLE
fix(tooltip): don’t assume that document.body is already accessible when the bundle inits

### PR DESCRIPTION
**Pull request by iamakulov**
## Description

When some script executes straight in `<head>`:

```html
<!doctype html>
<head>
  <script>console.log(document.body);</script>
</head>
<body>...</body>
```

this script doesn’t have access to any elements defined after it – including `document.body`.

```js
// console output from the script above
null
```

In https://github.com/appsmithorg/appsmith/pull/23556, we removed the `defer` attribute from the bundle script, making the script execute right in `<head>`. This broke some assumptions the `design-system-old` package had. 

This PR fixes that, making the code agnostic to where it executes.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual on main repo: tested that tooltips work in https://github.com/appsmithorg/appsmith/pull/23556

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by SatishGandham** [comment]
This looks good to me.
@albinAppsmith , @tanvibhakta  Can you have a look and merge it.

**Comment by tanvibhakta** [comment]
So this fix is in the old design system, and iirc there aren't any usages of the old design system in the main repo any more. Is this still needed? I'd prefer to close it. If this is a thing still happening with our new tool tip ([code](https://github.com/appsmithorg/design-system/tree/release/packages/design-system/src/Tooltip), [storybook](https://design-system.appsmith.com/?path=/story/design-system-tooltip--tooltip-story)) then the fix will need to be applied in that package.

**Comment by SatishGandham** [comment]
@tanvibhakta , this the PR that needs it, and it was raised when we were still using the old DS.
https://github.com/appsmithorg/appsmith/pull/23556

If the new popover implementation is still the same, we need the fix in new package.

**Comment by tanvibhakta** [comment]
Do you think the new tooltip implementation needs it?

**Comment by iamakulov** [comment]
Hey @tanvibhakta – sorry for the delay in the response here!

> Do you think the new tooltip implementation needs it?
The new tooltip implementation doesn’t need it.

But the old tooltip implementation is still included into the `design-system-old` package, which means the top-level module code from `design-system-old/src/Tooltip/index.tsx` :

```js
if (!portalContainer) {
  const tooltipPortalElement = document.createElement("div");
  tooltipPortalElement.id = rootElementId;
  document.body.append(tooltipPortalElement);
  portalContainer = document.getElementById(rootElementId);
}
```

still runs whenever we import `design-system-old`. With https://github.com/appsmithorg/appsmith/pull/23556, that code breaks the app (which is why this PR is needed).

> So this fix is in the old design system, and iirc there aren't any usages of the old design system in the main repo any more. Is this still needed? I'd prefer to close it.

I can still see a bunch of imports of `design-system-old` in the main codebase:

Screenshot 2023-06-03 at 23 49 06

but none of them import a tooltip indeed. So we can’t just close this PR, but we can remove the old Tooltip component completely instead – should I do that?

**Comment by tanvibhakta** [comment]
> which means the top-level module code from `design-system-old/src/Tooltip/index.tsx` still runs whenever we import `design-system-old`.

Ah I see - would it be enough to just remove the place where we've exported Tooltip from, in that case? I could in fact remove the exports for all the components we are no longer using from this package, but I'm hesitating to remove the components themselves because we only mean to deprecate this package, not delete it (or it's contents) entirely.

**Comment by iamakulov** [comment]
Oh okay, so I just tried to remove these:

https://github.com/appsmithorg/design-system/blob/aef8bf5ddc0548f104f65ec330e1a3630bbab69c/packages/design-system-old/src/index.ts#L181-L182

– but it turns out `Tooltip` is used in a bunch of other `design-system-old` components (e.g. `FilePickerV2`), and those _are_ used in the main repo. So we can neither remove `Tooltip` completely nor just remove its exports – it’s still needed and used by the code.

I’m afraid I don’t see any other option to solve this apart from merging this PR :/ (Very open to other ideas, though!) FWIW we’re making the same mirroring change in https://github.com/appsmithorg/appsmith/pull/23556/files#diff-0b85cc949c26fe4cae89f55b202ab9836607e783c03cc06a23aac4dbefb8ba4c, so maybe it’s okay?

**Comment by tanvibhakta** [comment]
sounds good, and sorry about the delay. Merging this now, will create a release by EOD and update it in the PR that depends on this.

**Review by tanvibhakta — APPROVED** [review]

**Comment by shadabbuchh** [comment]
This PR has been tested for the `design-system-old` Tooltip component. Tooltip is working as expected.

**Comment by iamakulov** [comment]
This might be unnecessary if https://github.com/appsmithorg/appsmith/pull/24374 is merged instead of https://github.com/appsmithorg/appsmith/pull/23556.

**Comment by tanvibhakta** [comment]
I'll close this for now, in that case.

**Pull request closed without merging**
