### PR TITLE
feat: Refactored Menu component

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

Added refactored menu component.

Fixes # (issue)
https://github.com/appsmithorg/appsmith/issues/19318

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual on storybook 
- Manual on main repo
- Jest
- Cypress

### Issues raised during DP testing
https://github.com/appsmithorg/design-system/pull/405#issuecomment-1461430677
https://github.com/appsmithorg/design-system/pull/405#issuecomment-1461515460
https://github.com/appsmithorg/design-system/pull/405#issuecomment-1466439736

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by tanvibhakta — APPROVED** [review]

**Comment by shadabbuchh** [comment]
### Design issues in this PR:

1. Wrong size for both sm & md.
2. Wrong background colour in active state.
3. Wrong font size in small variant (expected is 12px)

**Comment by laveena-en** [comment]
Functional:

1. Can we enable text-wrapping when the text>width of the item? (Also include a scrollbar to accommodate the text)

image

2. No error is shown when the width size entered is greater than the set max width of 280px
3. Can we add in a max limit for height as well?
4. Negative values are being accepted for width and height: https://www.loom.com/share/251f23a694a140b7907dd360f0620f06

Clarifications:
1. Would keyboard nav work for menu items that are disabled?

**Comment by albinAppsmith** [comment]
1. Wrong size for both sm & md. -> **Fixed**
2. Wrong background colour in active state. -> **Fixed**
3. Wrong font size in small variant (expected is 12px) -> **Fixed**

1. Can we enable text-wrapping when the text>width of the item? (Also include a scrollbar to accommodate the text) -> **This is happening because the story you are looking into is independent part of menu. This is for developers to get an idea of what all props the component accept. I have added an text wrap example in complete menu.**
2. Can we add in a max limit for height as well? -> **Max height is very subjective for now. Since design haven't defined any max height I have added like menu height can upto available space below.**
3. Negative values are being accepted for width and height -> ** This we don't need to worry about. This is storybook controls and if someone is passing negative values, we can treat that as a human error. For now we can ignore this and later we can figure out how to tackle this.**
4. Would keyboard nav work for menu items that are disabled? -> **No it won't. Because once an item is focusable using keyboard, an `enter` or `space` press will select the menu item which is in focus. Since disabled item is not selectable, keyboard nav also skips this.**

**Comment by shadabbuchh** [comment]
## Bugs after the latest fix:

### Menu Component:
1. Wrong size for both sm & md. (this is still not fixed)
2.  > FYI - For now I have kept ellipsis to the text if the text is overflowing. Reason being a multiline menu isn't a good UI. If this requires in future we can take it up that time.

For this, can we have a tooltip that appears with the full text once we hover over such a menu item?

3. The colour of the divider line is incorrect.
4. If the menu item is disabled, we can still focus on the `Open Menu` button and display the menu item by pressing the `Space` or `Enter` key. Is this because the button is still active?


### Button Component:

1. `isDisabled` control is not working.
2. The text inside the button always starts with uppercase even if we enter a text that starts with lowercase in the `children` control.
3. Editing the `startIcon`/`endIcon` throws an error. The only way you can change/edit the icons is by selecting the whole text & then pasting a new icon name.

**Comment by tanvibhakta** [comment]
> The text inside the button always starts with uppercase even if we enter a text that starts with lowercase in the children control.

This is an intentional design decision 

> Editing the startIcon/endIcon throws an error. The only way you can change/edit the icons is by selecting the whole text & then pasting a new icon name.

This is unfortunately an issue with storybook. Since it is evaluating as you type, it looks for the modules as you are typing, but of course those modules don't exist.

**Comment by shadabbuchh** [comment]
All the above identified issues have been fixed.

@albinAppsmith the ellipsis for the long menu item has been removed. Are we planning a different approach here?

**Comment by albinAppsmith** [comment]
@shadabbuchh  will take care of ellipsis in next phase after evaluating the use cases.

**Pull request merged**
