### PR TITLE
feat: Add different kinds of tag

### PR DESCRIPTION
**Pull request by tanvibhakta**
## Description

Zeplin: https://zpl.io/g8KLE9R
Fixes https://github.com/appsmithorg/appsmith/issues/19535

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

- Manual on storybook 
- Manual on main repo
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by albinAppsmith — APPROVED** [review]

**Comment by tanvibhakta** [comment]
generated alpha: 0.0.0-alpha-20230801084224

**Comment by Sripriya93** [comment]
As informed checked the color of each tag components
Observation:
Special tag: Expected color: #4a2185 Actual color: #401D73

Other than Special tag all the colors mentioned are as expected. Moving to Inprogress @tanvibhakta CC: @rohitagarwal88

**Comment by vasanthappsmith** [comment]
@shadabbuchh @Sripriya93 Please check this link for the Tag component's new colours to test. Meanwhile, I will delete all the projects which are not meant for the Engg and QA. 

Zeplin: https://zpl.io/g8KLE9R

**Comment by Sripriya93** [comment]
As informed checked only the color of each tag components. All the colors are as expected. Moving to done.

**Comment by tanvibhakta** [comment]
All tests have passed: https://github.com/appsmithorg/appsmith/pull/25804#issuecomment-1663833223

**Pull request merged**
